wandb:
  log_gradients: true  # Log model gradients every few steps
  entity_name: "dalbenziog"
  project_name: "CT_Kidney_Segmentation"
  experiment_name: "Spleen_Segmentation_Exp1"

data:
  image: "C:/Users/gabridal/Documents/CT_kidney_segmentation/dataset/imagesTr"
  label: "C:/Users/gabridal/Documents/CT_kidney_segmentation/dataset/labelsTr/"
  root_dir: "C:/Users/gabridal/Documents/CT_kidney_segmentation/dataset/'"
  num_class: 2
  cache_rate: 1.0
  num_workers: 2

log:
  name: "SpleenSegmentationNet"
  save_dir: "RESULTS"

loss:
  monai.losses.DiceCELoss:
    args: []
    kwargs:
      softmax: True
      to_onehot_y: True

net:
  monai.networks.nets.UNet:
    args: []
    kwargs:
      spatial_dims: 3
      in_channels: 1
      out_channels: 2
      channels: [16, 32, 64, 128, 256]
      strides: [2, 2, 2, 2]
      num_res_units: 2
      norm: "BATCH"


train:
  seed: 42
  batch_size: 2
  val_batch_size: 1
  max_epochs: 40
  val_interval: 5
  lr_scheduler: "cosine_decay"
  learning_rate: 0.0001
  augmentation:
    - monai.transforms.LoadImaged:
        args: []
        kwargs:
          keys: ["image", "label"]
    - monai.transforms.EnsureChannelFirstd:
        args: []
        kwargs:
          keys: ["image", "label"]
    - monai.transforms.ScaleIntensityRanged:
        args: []
        kwargs:
          keys: ["image"]
          a_min: -100
          a_max: 200
          b_min: 0.0
          b_max: 1.0
          clip: true
    - monai.transforms.Orientationd:
        args: []
        kwargs:
          keys: ["image", "label"]
          axcodes: "RAS"
    - monai.transforms.SpatialPadd: #ResizeWithPadOrCrop:
        args: [ ]
        kwargs:
          keys: [ "image", "label" ]
          spatial_size: [160,160,160]
    - monai.transforms.ResizeD:
        args: []
        kwargs:
          keys:
          - image
          - label
          mode:
          - trilinear
          - nearest
          spatial_size: [160,160,160]
          
valid:
  num_sample_images: 2
  roi_size: [160, 160, 160]  # Adjust dimensions as needed
  sw_batch_size: 4  
  augmentation:
    - monai.transforms.LoadImaged:
        args: []
        kwargs:
          keys: ["image", "label"]
    - monai.transforms.EnsureChannelFirstd:
        args: []
        kwargs:
          keys: ["image", "label"]
    - monai.transforms.ScaleIntensityRanged:
        args: []
        kwargs:
          keys: ["image"]
          a_min: -100
          a_max: 200
          b_min: 0.0
          b_max: 1.0
          clip: true
    - monai.transforms.Orientationd:
        args: []
        kwargs:
          keys: ["image", "label"]
          axcodes: "RAS"
    - monai.transforms.SpatialPadd: #ResizeWithPadOrCrop:
        args: [ ]
        kwargs:
          keys: [ "image", "label" ]
          spatial_size: [160,160,160]
    - monai.transforms.ResizeD:
        args: []
        kwargs:
          keys:
          - image
          - label
          mode:
          - trilinear
          - nearest
          spatial_size: [160,160,160]





